// <auto-generated />
using System;
using HomeInventory.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeInventory.Server.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20201030120011_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("HomeInventory.Shared.Entities.Part", b =>
                {
                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeCode")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Company", "Id");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("HomeInventory.Shared.Entities.PartTran", b =>
                {
                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TranId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Adjustment")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryUserName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TranDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Company", "TranId");

                    b.HasIndex("Company", "EntryUserName");

                    b.HasIndex("Company", "PartId");

                    b.ToTable("PartTrans");
                });

            modelBuilder.Entity("HomeInventory.Shared.Entities.User", b =>
                {
                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Company", "UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Company = "HOME",
                            UserName = "jdbaur"
                        });
                });

            modelBuilder.Entity("HomeInventory.Shared.Entities.PartTran", b =>
                {
                    b.HasOne("HomeInventory.Shared.Entities.User", "EntryUser")
                        .WithMany("PartTrans")
                        .HasForeignKey("Company", "EntryUserName");

                    b.HasOne("HomeInventory.Shared.Entities.Part", "Part")
                        .WithMany("PartTrans")
                        .HasForeignKey("Company", "PartId");

                    b.Navigation("EntryUser");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("HomeInventory.Shared.Entities.Part", b =>
                {
                    b.Navigation("PartTrans");
                });

            modelBuilder.Entity("HomeInventory.Shared.Entities.User", b =>
                {
                    b.Navigation("PartTrans");
                });
#pragma warning restore 612, 618
        }
    }
}
